# This file is managed by 'repo_helper'. Don't edit it directly.
---

os: linux
language: python
dist: focal
cache: pip
python:
  - '3.6'
arch:
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis

script:
  - tox -vv

stages:
  - test
  - deploy_conda

jobs:
  allow_failures:
    - arch: arm64
