[build-system]
requires = [ "setuptools>=40.6.0", "wheel>=0.34.2",]
build-backend = "setuptools.build_meta"

[project]
name = "domdf_python_tools"
version = "2.8.1"
description = "Helpful functions for Pythonâ€‚ðŸâ€‚ðŸ› ï¸"
readme = "README.rst"
keywords = [ "utilities",]
dynamic = [ "requires-python", "classifiers", "dependencies",]

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/domdfcoding/domdf_python_tools"
"Issue Tracker" = "https://github.com/domdfcoding/domdf_python_tools/issues"
"Source Code" = "https://github.com/domdfcoding/domdf_python_tools"
Documentation = "https://domdf_python_tools.readthedocs.io/en/latest"

[project.optional-dependencies]
dates = [ "pytz>=2019.1",]
testing = [ "pytest>=6.2.0", "pytest-regressions>=2.0.2",]
all = [ "pytest>=6.2.0", "pytest-regressions>=2.0.2", "pytz>=2019.1",]

[tool.mkrecipe]
conda-channels = [ "domdfcoding", "conda-forge",]
extras = [ "dates",]
license-key = "LGPLv3+"
